
---

  - name: Install epel-release
    yum:  name=epel-release state=installed
    
  - name: Upgrade all packages
    yum: name=* state=latest

  - name: Install base packages
    yum: name={{ item }} state=present
    with_items:
      - nano
      - vim
      - yum-utils
      - net-snmp
      - net-snmp-utils
      - lsof
      - mlocate
      - git
      - zsh
      - curl
      - screen
      - wget
      - net-tools
      - telnet
      - unzip
      - mailx

  - name: Snmp configuration
    notify:
      - reload snmp
    template:
      src=snmpd.conf.j2
      dest=/etc/snmp/snmpd.conf
      owner=root
      group=root
      mode=0600

  - name: reload snmp
    service: name=snmpd state=reloaded

